apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag.fullname" . }}
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "rag.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rag.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rag.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          volumeMounts:
            - name: collections
              mountPath: /opt/app-root/src/collections.json
              subPath: collections.json
            - name: prompt
              mountPath: /opt/app-root/src/prompt.txt
              subPath: prompt.txt
          env:
            - name: APP_TITLE
              value: Chat with your Knowledge Base
            - name: SHOW_TITLE_IMAGE
              value: "True"
            - name: INFERENCE_SERVER_URL
              value: "{{ .Values.env.model_url }}"
            - name: MODEL_NAME
              value: "{{ .Values.env.model_name }}"
            - name: MODEL_TOKENS
              value: "2048"
            - name: TOP_P
              value: "0.95"
            - name: TEMPERATURE
              value: "0.5"
            - name: MILVUS_HOST
              value: "{{ .Values.env.milvus_host }}"
            - name: MILVUS_PORT
              value: "19530"
            - name: MILVUS_USER
              value: "{{ .Values.env.milvus_user }}"
            - name: MILVUS_PASSWORD
              value: "{{ .Values.env.milvus_password }}"
            - name: MILVUS_COLLECTIONS_FILE
              value: /opt/app-root/src/collections.json
            - name: DEFAULT_COLLECTION
              value: "{{ .Values.env.default_collection }}"
            - name: PROMPT_FILE
              value: prompt.txt
            - name: MAX_RETRIEVAL_DOCS
              value: "3"
            - name: SCORE_THRESHOLD
              value: "0.99"
            - name: EMBEDDING_MODEL
              value: "{{ .Values.env.embedding_model }}"
            {{- with .Values.phoenix }}
            - name: PHOENIX_COLLECTOR_ENDPOINT
              value: {{ .endpoint | quote }}
            - name: PHOENIX_PORT
              value: {{ .port | quote }}
            {{- end -}}
            {{- if .Values.env.api_key }}
            - name: API_KEY
              value: "{{ .Values.env.api_key }}"
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      volumes:
        - name: collections
          configMap:
            defaultMode: 420
            items:
              - key: collections.json
                path: collections.json
            name: {{ include "rag.fullname" . }}-collections
        - name: prompt
          configMap:
            defaultMode: 420
            items:
              - key: prompt.txt
                path: prompt.txt
            name: {{ include "rag.fullname" . }}-prompt
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
