replicaCount: 1
image:
  repository: harbor.nsx.techlab.netone.co.jp/library/rag-gradio
  tag: "1.7"
  pullPolicy: Always
env:
  api_key: ""
  model_url: "https://phi4.demo.svc.cluster.local"
  model_name: "phi4"
  milvus_host: "milvus.milvus.svc.cluster.local"
  milvus_port: "19530"
  milvus_user: "your_milvus_username"
  milvus_password: "your_milvus_password"
  default_collection: "nosblog_embeddings"
  embedding_model: "intfloat/multilingual-e5-small"
  temperature: "1"
imagePullSecrets: []
service:
  type: ClusterIP
  port: 7860
phoenix:
  endpoint: "http://phoenix.phoenix.svc.cluster.local:6006/v1/traces"
  port: 6006
route:
  enabled: true
  tls:
    enabled: true
    termination: edge
    key: ""
    destinationCACertificate: ""
    caCertificate: ""
    certificate: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
