{{- if ne .Values.route.enabled false }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "gradio.fullname" . }}
  labels:
    {{- include "gradio.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "gradio.fullname" . }}
  port:
    targetPort: {{ .Values.service.port }}
  {{- if ne .Values.route.tls.enabled false }}
  tls:
    termination: {{ default "edge" .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: None
  {{- if .Values.route.tls.key }}
    key: |-
      {{- .Values.route.tls.key | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: |-
      {{- .Values.route.tls.destinationCACertificate | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.caCertificate }}
    caCertificate: |-
      {{- .Values.route.tls.caCertificate | nindent 6 }}
  {{- end }}
  {{- if .Values.route.tls.certificate }}
    certificate: |-
      {{- .Values.route.tls.certificate | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }} 